# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Temporary Notebook"

# A description of your site for meta tag, search engine results.
description: "Nothing is more permanent than the temporary"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://samatas.net"

# Favicon
favicon: /images/favicon.png

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
# disqus: samatasnet

# Colors
palette: darkEmerald
palettes:
  blue:
    sass:
      accent: '#2d72d9'
  green:
    sass:
      accent: '#00debc'
  orange:
    sass:
      accent: '#ff5000'
  darkEmerald:
    sass:
      accent: '#003d00'

# Site footer
footer:
  content: "&copy; 2019 Michael Samatas all rights reserved."
  links:
    - text: Based on the Scriptor-Jekyll-Theme
      url: 'https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme'
      new_window: true
  has_social: true

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:title

markdown: kramdown

# Sass
sass:
  indentWidth: 4
  style: nested
  precision: 10
